routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->middleware('role:admin')->group(function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    Route::resource('companies', 'CompanyController');
    Route::resource('employees', 'EmployeeController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'name',
        'email',
        'logo_id',
        'website'
    ];

    public function logo()
    {
        return $this->hasOne('App\Logo', 'id', 'logo_id');
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Company;
use App\Http\Requests\StoreCompany;
use App\Http\Requests\UpdateCompany;
use App\Logo;
use App\Mail\NewCompanyEntered;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);

        return view('admin.companies.index', ['companies' => $companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCompany $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(StoreCompany $request)
    {
        $storedLogo = false;
        if($request->hasFile('logo')){
            $logo = new Logo();
            $storedLogo = $logo->storeLogo($request->file('logo'));
        }

        $company = Company::create([
            'name' => $request->name,
            'email' => $request->email,
            'website' => $request->website,
            'logo_id' => ($storedLogo)?$storedLogo->id:null
        ]);

        Mail::to($request->user())->send(new NewCompanyEntered($company));

        return redirect(route('companies.index'))->with('success', 'Company was successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);

        return view('admin.companies.show', ['company' => $company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);

        return view('admin.companies.edit', ['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCompany $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UpdateCompany $request, $id)
    {
        $company = Company::find($id);

        $storedLogo = $company->logo;
        $oldLogoId = false;
        if($request->hasFile('logo')){
            //delete old logo from storage and from table
            if(!is_null($company->logo)){
                $oldLogoId = $company->logo->id;
            }

            //store new logo
            $logo = new Logo();
            $storedLogo = $logo->storeLogo($request->file('logo'));
        }

        $company->update([
            'name' => $request->name,
            'email' => $request->email,
            'website' => $request->website,
            'logo_id' => ($storedLogo)?$storedLogo->id:null
        ]);

        if($oldLogoId){
            Logo::deleteLogo($oldLogoId);
        }

        return redirect(route('companies.index'))->with('success', 'Company was successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);

        if(!is_null($company)){
            if(!is_null($company->logo_id)){
                Logo::deleteLogo($company->logo_id);
            }

            $company->delete();
        }

        return redirect(route('companies.index'));
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <h1>Companies</h1>

    <a href="{{route('companies.index')}}" class="btn btn-secondary"><- Back</a>

    <form method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email">
            <p class="help-block">* Not required</p>
        </div>

        <div class="form-group">
            <label for="website">Website</label>
            <input type="text" class="form-control" id="website" name="website">
            <p class="help-block">* Not required</p>
        </div>

        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="logo" name="logo">
                <label class="custom-file-label" for="logo">Upload logo</label>
                <p class="help-block">* Not required</p>
            </div>
            New logo:
            <img id="new_logo" src="#" alt="new logo" class="col-3"/>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Create
            </button>
        </div>
    </form>
@endsection

@section('custom-script')
    <script>
        $( document ).ready(function() {
            $('#logo').change(function(){
                var input = this;
                var url = $(this).val();
                var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg"))
                {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#new_logo').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
                else
                {
                    $('#new_logo').attr('src', '#');
                }
            });
        });
    </script>
@endsection

resources/views/admin/companies/edit.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <h1>Edit company: {{$company->name}}</h1>

    <a href="{{route('companies.index')}}" class="btn btn-secondary"><- Back</a>

    <form method="POST" action="{{ route('companies.update', $company->id) }}" enctype="multipart/form-data">
        @csrf
        {{method_field('PUT')}}

        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{$company->name}}" required>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{$company->email}}">
            <p class="help-block">* Not required</p>
        </div>

        <div class="form-group">
            <label for="website">Website</label>
            <input type="text" class="form-control" id="website" name="website" value="{{$company->website}}">
            <p class="help-block">* Not required</p>
        </div>

        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="logo" name="logo">
                <label class="custom-file-label" for="logo">Upload logo</label>
                <p class="help-block">* Not required</p>
            </div>
            <div class="row">
                <div class="col-6">
                    Current logo:
                    <img id="current_logo" src="{{$company->logo->getUrl()}}" alt="current logo" class="col-3"/>
                </div>
                <div class="col-6">
                    New logo:
                    <img id="new_logo" src="#" alt="new logo" class="col-3"/>
                </div>
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Update
            </button>
        </div>
    </form>
@endsection

@section('custom-script')
    <script>
        $( document ).ready(function() {
            $('#logo').change(function(){
                var input = this;
                var url = $(this).val();
                var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg"))
                {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#new_logo').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
                else
                {
                    $('#new_logo').attr('src', '#');
                }
            });
        });
    </script>
@endsection

resources/views/admin/companies/index.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="{{route('companies.create')}}" class="btn btn-success">Create new company</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{route('companies.index')}}">Companies</a>
        </li>
    </ul>

    <h1>Companies</h1>

    @if(!is_null($companies))
        <table id="companies">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Logo</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Website</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($companies as $company)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>
                        <a href="{{route('companies.show', $company->id)}}">
                            @if(!is_null($company->logo))
                                <img class="img-fluid" style="max-width: 25%; max-height: 25%" src="{{$company->logo->getUrl()}}">
                            @else
                                <img class="img-fluid" style="max-width: 25%; max-height: 25%" src="{{asset('images/no-image-icon.png')}}">
                            @endif
                        </a>
                    </td>
                    <td>{{$company->name}}</td>
                    <td>{{$company->email}}</td>
                    <td>{{$company->website}}</td>
                    <td class="row">
                        <div class="btn-group" role="group">
                            <a href="{{route('companies.show', $company->id)}}" class="btn btn-info">Show</a>
                            <a class="btn btn-warning" href="{{route('companies.edit', $company->id)}}">Edit</a>
                            <form method="POST" action="{{route('companies.destroy', $company->id)}}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $companies->links() }}
    @else
        Empty
    @endif
@endsection

@section('custom-script')
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#companies').DataTable();
        } );
    </script>
@endsection

resources/views/admin/companies/show.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>
        </div>
    </nav>

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{route('companies.index')}}">Companies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled"> > </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{{$company->name}}</a>
        </li>
    </ul>

    <h1>{{$company->name}}</h1>
    <a href="{{route('companies.index')}}" class="btn btn-secondary"><- Back</a>

    <div class="row">
        <div class="col-3">
            @if(!is_null($company->logo))
                <img class="img-fluid" src="{{$company->logo->getUrl()}}">
            @else
                <img class="img-fluid" src="{{asset('images/no-image-icon.png')}}">
            @endif
        </div>
        <div class="col-9">
            <p><b>Name:</b> {{$company->name}}</p>
            <p><b>Email:</b> {{$company->email}}</p>
            <p><b>Website:</b> {{$company->website}}</p>
            <div class="row">
                <div class="btn-group" role="group">
                    <a class="btn btn-warning" href="{{route('companies.edit', $company->id)}}">Edit</a>
                    <form method="POST" action="{{route('companies.destroy', $company->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}

                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection