routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->middleware('role:admin')->group(function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    Route::resource('companies', 'CompanyController');
    Route::resource('employees', 'EmployeeController');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'company_id',
        'email',
        'phone'
    ];

    public function company()
    {
        return $this->hasOne('App\Company', 'id', 'company_id');
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Company;
use App\Employee;
use App\Http\Requests\StoreEmployee;
use App\Http\Requests\UpdateEmployee;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate(10);

        return view('admin.employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();

        return view('admin.employees.create', ['companies' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreEmployee $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(StoreEmployee $request)
    {
        Employee::create($request->all());

        return redirect(route('employees.index'))->with('success', 'Employee was successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);
        $companies = Company::all();

        return view('admin.employees.show', ['employee' => $employee, 'companies' => $companies]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $companies = Company::all();

        return view('admin.employees.edit', ['employee' => $employee, 'companies' => $companies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateEmployee $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UpdateEmployee $request, $id)
    {
        $employee = Employee::find($id);
        $employee->update($request->all());

        return redirect(route('employees.index'))->with('success', 'Employee was successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);

        if(!is_null($employee)){
            $employee->delete();
        }

        return redirect(route('employees.index'));
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <h1>Employees</h1>

    <a href="{{route('employees.index')}}" class="btn btn-secondary"><- Back</a>

    <div class="row">
        <form class="col-6" method="POST" action="{{ route('employees.store') }}">
            @csrf

            <div class="form-group">
                <label for="first_name">First name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" required>
            </div>

            <div class="form-group">
                <label for="last_name">Last name</label>
                <input type="text" class="form-control" id="last_name" name="last_name" required>
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <label for="company_id">Company</label>
                <select class="form-control" id="company_id" name="company_id">
                    <option>Choose company</option>
                    @foreach($companies as $company)
                        <option value="{{$company->id}}">{{$company->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email">
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" id="phone" name="phone">
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    Create
                </button>
            </div>
        </form>
    </div>

@endsection

resources/views/admin/employees/edit.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <h1>Employees</h1>

    <a href="{{route('employees.index')}}" class="btn btn-secondary"><- Back</a>

    <div class="row">
        <form class="col-6" method="POST" action="{{ route('employees.update', $employee->id) }}">
            @csrf
            {{method_field('PUT')}}

            <div class="form-group">
                <label for="first_name">First name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{$employee->first_name}}" required>
            </div>

            <div class="form-group">
                <label for="last_name">Last name</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{$employee->last_name}}" required>
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <label for="company_id">Company</label>
                <select class="form-control" id="company_id" name="company_id">
                    @foreach($companies as $company)
                        @if($employee->company_id == $company->id)
                            <option value="{{$company->id}}" selected>{{$company->name}}</option>
                        @else
                            <option value="{{$company->id}}">{{$company->name}}</option>
                        @endif
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="{{$employee->email}}">
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" id="phone" name="phone" value="{{$employee->phone}}">
                <p class="help-block">* Not required</p>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    Update
                </button>
            </div>
        </form>
    </div>

@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="{{route('employees.create')}}" class="btn btn-success">Create new employee</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{route('employees.index')}}">Employees</a>
        </li>
    </ul>

    <h1>Employees</h1>

    @if(!is_null($employees))
        <table id="employees">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
                @foreach($employees as $employee)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$employee->first_name}}</td>
                    <td>{{$employee->last_name}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->phone}}</td>
                    <td class="row">
                        <div class="btn-group" role="group">
                            <a href="{{route('employees.show', $employee->id)}}" class="btn btn-info">Show</a>
                            <a href="{{route('employees.edit', $employee->id)}}" class="btn btn-warning">Edit</a>
                            <form method="POST" action="{{route('employees.destroy', $employee->id)}}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        {{ $employees->links() }}
    @else
        Empty
    @endif
@endsection

@section('custom-script')
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#employees').DataTable();
        } );
    </script>
@endsection

resources/views/admin/employees/show.blade.php
@extends('layouts.admin.admin')

@include('layouts.admin.errors.errors')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span>Toggle Sidebar</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>
        </div>
    </nav>

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{route('employees.index')}}">Employees</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled"> > </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{{$employee->first_name}} {{$employee->last_name}}</a>
        </li>
    </ul>

    <h1>{{$employee->first_name}} {{$employee->last_name}}</h1>
    <a href="{{route('employees.index')}}" class="btn btn-secondary"><- Back</a>

    <div class="row">
        <div class="col-9">
            <p><b>Name:</b> {{$employee->name}}</p>
            <p><b>Email:</b> {{$employee->email}}</p>
            <p><b>Website:</b> {{$employee->website}}</p>
            <p><b>Company:</b> {{$employee->company->name}}</p>
            <div class="row">
                <div class="btn-group" role="group">
                    <a href="{{route('employees.edit', $employee->id)}}" class="btn btn-warning">Edit</a>
                    <form method="POST" action="{{route('employees.destroy', $employee->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}

                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection